### ISSUE TITLE
Question about the bricked badges

### ISSUE THREAD

**Issue by MicaelJarniac** [Paradoxis/SHA2017#1]
Could bricked badges (due to the buggy 'The Legend of Zelda' or even something else) be unbricked, for example by reflashing?

By the way, I didn't attend to the event, just finished reading a post of yours about it and really wanted to ask that.

**Comment by Paradoxis** [comment]
Yes! Luckily you could simply re-flash the badges although it was a pain in the ass to have to go there and get help doing so if you didn’t understand how to

It’s been a while but I also recall that someone pwned the flashing bar though so I whenever you’d re-flash your badge you’d get rick rolled or something meaning at that point you were screwed until they fixed it (don’t quote me on that though, I need to refresh my memory)

**Comment by MicaelJarniac** [comment]
I guess it wouldn't make much sense if a malfunctioning software like that caused it to brick beyond repair, as I think even bricking it on purpose with just software should be a challenge on its own, but I'm quite new to all of this so I decided to ask anyway.

And infecting the flashing station was probably just a natural step for the event it seems xD
I think the badge creators made firmware images readily available so people more familiar with it could flash themselves.

Thanks for clarifying that to me :D and also for open-sourcing your projects on the event. I'll probably see if I can do something with it on my ESP8266.
